version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwordmtm
      MYSQL_DATABASE: database-group2
      MYSQL_USER: admin
      MYSQL_PASSWORD: passwordmtm
    ports:
      - "3308:3306" 
  app:
    image: wordpress
    ports:
      - "3003:3000"
    depends_on: 
      - db
    links:
      - db
    environment:         
      DB_USER: admin
      DB_NAME: database-group2
      DB_PASSWORD: passwordmtm
      DB_HOST: db
      #RAILS_ENV: production
      #RAILS_LOG_TO_STDOUT: 1
      #SECRET_KEY_BASE:  <GENERATE ONE USING rails secret>
